# Third-party library for interactive CLI prompts
import questionary


def choose_commit(commits: list[str]) -> str:
    """
    Prompt the user to select a commit message from a list of suggestions.

    Args:
        commits (list[str]):
            A list of commit message suggestions generated by the AI.

    Returns:
        str:
            The commit message selected by the user.

    Raises:
        KeyboardInterrupt:
            If the user cancels the prompt (e.g. Ctrl+C).
    """

    # Display an interactive selector
    choice: str | None = questionary.select(
        "Proposed commit messages:",
        choices=commits,
        qmark="",
    ).ask()

    # Questionary returns None if the user aborts the prompt
    if choice is None:
        raise KeyboardInterrupt("Commit selection aborted by user.")

    return choice
